apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: webapp
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: webapp
    spec:
      containers:
      - name: webapp
        image: coatsn/angular-server
        ports:
        - containerPort: 3000
        imagePullPolicy: IfNotPresent
